# Generated by Django 5.2.6 on 2025-10-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_image_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modifiedOn', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icon', models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Portátil e telemóvel'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha da árvore'), ('lni-layers', 'Camadas'), ('lni-layers', 'Camadas')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
